from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('predict/', views.home, name="predict"),
    path('crop-cycle/', views.crop_cycle, name="crop_cycle"),
    path('start-cycle/', views.start_cycle, name="start_cycle"),
    path('mark-done/<int:task_id>/', views.mark_done, name="mark_done"),
    path('report/', views.report_view, name="report"),
    # path("admin-panel/login/", views.admin_login, name="admin_login"),
    path("admin-panel/dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("admin-panel/logout/", views.admin_logout, name="admin_logout"),
    path("register/", views.user_register, name="user_register"),
    path("login/", views.user_login, name="user_login"),
    path("logout/", views.user_logout, name="user_logout"),
    path("dashboard/", views.user_dashboard, name="user_dashboard"),
    path("admin-panel/add-crop-cycle/", views.add_crop_cycle, name="add_crop_cycle"),
    path("my-sessions/", views.my_sessions, name="my_sessions"),
    path("reports/", views.all_reports, name="all_reports"),
    path("report/pdf/", views.download_report_pdf, name="download_report_pdf"),
    path("tasks/", views.all_tasks, name="all_tasks"),
    path("admin-panel/crops/", views.admin_crops, name="admin_crops"),
    path("admin-panel/crops/add/", views.admin_add_crop, name="admin_add_crop"),
    path("admin-panel/crops/delete/<int:crop_id>/", views.admin_delete_crop, name="admin_delete_crop"),
    path("admin-panel/crops/edit/<int:crop_id>/", views.admin_edit_crop, name="admin_edit_crop"),
    path("crop-search/", views.crop_search, name="crop_search"),
    path("crop-details/", views.crop_details, name="crop_details"),
    path("start-manual-cycle/", views.start_manual_cycle, name="start_manual_cycle"),
    path("chatbot/", views.chatbot_api, name="chatbot_api"),
    path("feedback/", views.feedback_submit, name="feedback_submit"),
    path("admin-panel/cycles/", views.admin_manage_cycles, name="admin_manage_cycles"),
    path("admin-panel/cycles/edit/<int:cycle_id>/", views.admin_edit_cycle, name="admin_edit_cycle"),
    path("admin-panel/cycles/delete/<int:cycle_id>/", views.admin_delete_cycle, name="admin_delete_cycle"),
    path("admin-panel/feedback/", views.admin_feedback_view, name="admin_feedback_view"),
    path("admin-panel/users/", views.admin_users_view, name="admin_users_view"),
    path("admin-panel/users/delete/<int:user_id>/", views.admin_delete_user, name="admin_delete_user"),
    path("my-sessions/delete/<int:session_id>/", views.delete_session, name="delete_session"),
]
