# Generated by Django 5.2.10 on 2026-01-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50, unique=True)),
                ('season', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('watering', models.TextField()),
                ('fertilizer', models.TextField()),
                ('common_diseases', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
