# Generated by Django 5.2.10 on 2026-01-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0002_cropdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropdetails',
            name='image_url',
        ),
        migrations.AddField(
            model_name='cropdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
