# Generated by Django 5.2.10 on 2026-01-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0003_remove_cropdetails_image_url_cropdetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('greeting', 'Greeting'), ('dashboard', 'Dashboard Help'), ('crop', 'Crop Related'), ('stage', 'Stage Related'), ('general', 'General Agriculture')], max_length=50)),
                ('crop_name', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_name', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.TextField(help_text='Comma-separated keywords (e.g. water, irrigation)')),
                ('response', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
