# Generated by Django 5.1.6 on 2026-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_app', '0006_alter_chatbotknowledge_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
